# Generated by Django 6.0.2 on 2026-03-08 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='License must contain 3 uppercase letters followed by 5 digits.', regex='^[A-Z]{3}\\d{5}$')]),
        ),
    ]
